name: Lint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.1'
    - name: Install dependencies
      run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - name: Check the code
      run: bash tools/check.sh
